baseurl = "https://example.com/"
languageCode = "en-US"
title = "R-Ladies Seattle"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "seattle.jpg"
  author = "R-Ladies Seattle"
  description = "R-Ladies Seattle Blogdown Site"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Meetup        = "rladies-seattle"
  Slack         = "rladies-sea"
  Twitter       = "RLadiesSeattle"
  Github        = "rladies-seattle"
  Email         = "info@rladies.org"

## Main Menu
[[menu.main]]
  name = "events"
  weight = 100
  identifier = "events"
  url = "https://www.meetup.com/{{ .Site.Params.Social.Meetup }}/events/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
